# Generated by Django 5.2.15 on 2026-07-11 15:30

import django.db.models.deletion
from django.db import migrations, models

def transfer_images_to_cloudinary(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product') 
    for product in Product.objects.all():
        if product.image and not str(product.image).startswith('http'):
            try:
                name = product.image.name
                with product.image.open('rb') as f:
                    product.image.save(name, f, save=True)
                print(f"Успешно перенесено в Cloudinary: {product.name}")
            except Exception as e:
                print(f"Ошибка при переносе {product.name}: {e}")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('pieces', models.PositiveIntegerField(default=0, help_text='Number of LEGO pieces')),
                ('age_min', models.PositiveIntegerField(default=6, help_text='Minimum recommended age')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Запускаем скрипт переноса сразу после создания таблиц!
        migrations.RunPython(transfer_images_to_cloudinary),
    ]